AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - tmp/**/*
    - vendor/**/*
    - db/**/*

Rails:
  Enabled: true

Documentation:
  Enabled: false

Layout/EmptyLines:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/IndentHash:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Metrics/LineLength:
  Enabled: true
  Max: 120

Metrics/MethodLength:
  Max: 15

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

Rails/ApplicationRecord:
  Enabled: false

Style/BlockDelimiters:
  Exclude:
    - spec/**/*/.rb

Style/ClassAndModuleChildren:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/SingleLineBlockParams:
  Enabled: false

Style/SignalException:
  EnforcedStyle: semantic

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: '{}'
    '%i': '{}'
    '%w': '{}'

Style/ParallelAssignment:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
