AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - tmp/**/*
    - vendor/**/*
    - db/**/*
    
Bundler/OrderedGems:
  Enabled: false
  
Lint/AmbiguousRegexpLiteral:
  Enabled: false

Rails:
  Enabled: true

Rails/Delegate:
  Enabled: false

Rails/FilePath:
  Enabled: false

Documentation:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/IndentHash:
  Enabled: true
  EnforcedLastArgumentHashStyle: ignore_implicit

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Lint/UnusedMethodArgument:
  Enabled: false

Lint/UnusedBlockArgument:
  Enabled: false

Metrics/LineLength:
  Enabled: true
  Max: 120

Metrics/MethodLength:
  Max: 15

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

Rails/ApplicationRecord:
  Enabled: false

Style/BlockDelimiters:
  Exclude:
    - spec/**/*.rb

Style/AndOr:
  EnforcedStyle: conditionals

Style/ClassAndModuleChildren:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/SingleLineBlockParams:
  Enabled: false

Style/SignalException:
  EnforcedStyle: semantic

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: '{}'
    '%i': '{}'
    '%w': '{}'

Style/SymbolArray:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
